mariadb:
  #use url or host, port and database
  url: "jdbc:mariadb://localhost:3306/quiz_game"
  host: "localhost"
  port: 3306
  user: "root"
  password: "password"
  database: "quiz_game"

categories:
  - prova:
      - a
      - b
      - c
  - prova1:
      - d
      - e
      - f