# Database Configuration
database:
  host: "localhost"
  port: 3306
  name: "quiz_game"
  url: "?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
  username: "root"
  password: ""

# Messages Configuration
messages:
  notAPlayer: "&4You are not a player!"
  format: "&7[%0%&7] %1%&f\n"
  hover: "&e&lClick &6for answer&6: %5%&6!"
  startGame: "&4Start a game first!"
  invalidPlayer: "&4Please use this command as a player"
  invalidCategory: "&4Invalid category. Available categories:\n&f%0%"
  invalidAnswer: "&4Invalid answer."
  points: "&6Congratulations! You &e&learned &f%0% &6points"
  showPoint: "&6%0%'s score: %1% points"
  separator: "\n"

# Categories Configuration
categories:
  geography:
    category: "&9Geography"
    questions:
      capital:
        question: "&6What is the capital of France?"
        answers:
          paris:
            answer: "&aParis"
            points: 1.0
          london:
            answer: "&aLondon"
            points: 0.0
          rome:
            answer: "&aRome"
            points: 0.0
          list:
            - "paris"
            - "london"
            - "rome"
      river:
        question: "&bWhich river is the longest in the world?"
        answers:
          nile:
            answer: "&aNile River"
            points: 1.0
          amazon:
            answer: "&aAmazon River"
            points: 0.0
          yangtze:
            answer: "&aYangtze River"
            points: 0.0
          list:
            - "nile"
            - "amazon"
            - "yangtze"
      list:
        - "capital"
        - "river"
  movies:
    category: "&4Movies"
    questions:
      oscar:
        question: "&6Which movie won the Best Picture Oscar in 2020?"
        answers:
          parasite:
            answer: "&aParasite"
            points: 1.0
          joker:
            answer: "&aJoker"
            points: 0.0
          1917:
            answer: "&a1917"
            points: 0.0
          list:
            - "parasite"
            - "joker"
            - "1917"
      actor:
        question: "&6Who played the role of Iron Man in the Marvel movies?"
        answers:
          robert_downey_jr:
            answer: "&aRobert Downey Jr."
            points: 1.0
          chris_evans:
            answer: "&aChris Evans"
            points: 0.0
          tom_holland:
            answer: "&aTom Holland"
            points: 0.0
          list:
            - "robert_downey_jr"
            - "chris_evans"
            - "tom_holland"
      list:
        - "oscar"
        - "actor"
  list:
    - "geography"
    - "movies"