# Database Configuration
database:
  host: "localhost"
  port: 3306
  name: "quiz_game"
  username: "root"
  password: ""

# Messages Configuration
messages:
  notAPlayer: "&4You are not a player!"
  format: "&7[&6%0%&7] &6%1%:&f\n"
  hover: "&7[&6Click for &6&lanswer&6!&7] %0% %1% %2% %3% %4% %5%"
  startGame: "Start a game first!"
  invalidPlayer: "Please use this command as a player"
  invalidCategory: "Invalid category."
  invalidAnswer: "Invalid answer."
  points: "Congratulations! You earned %0% points"
  showPoint: "&6%0%'s score: %1% points"
  separator: "\n"

# Categories Configuration
categories:
  geography:
    category: "Geography"
    questions:
      capital:
        question: "What is the capital of France?"
        answers:
          paris:
            answer: "&6Paris"
            points: 1.0
          london:
            answer: "&aLondon"
            points: 0.0
          rome:
            answer: "&aRome"
            points: 0.0
          list:
            - paris
            - london
            - rome
      river:
        question: "Which river is the longest in the world?"
        answers:
          nile:
            answer: "&6Nile River"
            points: 1.0
          amazon:
            answer: "&aAmazon River"
            points: 0.0
          yangtze:
            answer: "&aYangtze River"
            points: 0.0
          list:
            - nile
            - amazon
            - yangtze
      list:
        - "capital"
        - "river"
  movies:
    category: "Movies"
    questions:
      oscar:
        question: "Which movie won the Best Picture Oscar in 2020?"
        answers:
          parasite:
            answer: "Parasite"
            points: 1.0
          joker:
            answer: "Joker"
            points: 0.0
          1917:
            answer: "1917"
            points: 0.0
          list:
            - parasite
            - joker
            - 1917
      actor:
        question: "Who played the role of Iron Man in the Marvel movies?"
        answers:
          robert_downey_jr:
            answer: "Robert Downey Jr."
            points: 1.0
          chris_evans:
            answer: "Chris Evans"
            points: 0.0
          tom_holland:
            answer: "Tom Holland"
            points: 0.0
          list:
            - robert_downey_jr
            - chris_evans
            - tom_holland
      list:
        - "oscar"
        - "actor"
  list:
    - "geography"
    - "movies"