name: QuizGame
version: '${project.version}'
main: dev.sweety.quizgame.QuizGame
api-version: '1.17'
load: STARTUP
authors: [ SweetyDreams_ ]
description: Quiz Game
website: www.sweety.gay

commands:
  play:
    aliases: [ quiz, quiz-game, qg, quizgame ]
    description: start game
    permission: quizgame.play
  answer:
    description: answer to the question
    permission: quizgame.play
  qreload:
    aliases: [ reload ]
    description: reload config
    permission: quizgame.staff.reload
  score:
    description: show player score
    permission: quizgame.score